name: CI

on:
  # run once a day at noon UTC
  schedule:
    - cron: "0 12 * * *"
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"

concurrency:
  group: "${{ github.ref }}-${{ github.head_ref }}"
  cancel-in-progress: true

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: ["ubuntu-latest", "macOS-latest",]
        python-version: ["3.7", "3.8", "3.9"]

    steps:
    - uses: actions/checkout@v2

    - name: Setup python ${{ matrix.py_version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Display Python version
      run: python -c "import sys; print(sys.version)"

    - name: Install dependencies
      run: |
        pip install --upgrade setuptools pip
        pip install --upgrade .

        # Test
        pip install pytest pytest-cov pytest-pep8 codecov coverage
        pip install https://github.com/selimsami/qforce_examples/archive/master.zip

    - name: Run test
      run: |
        coverage run --source=qforce $(which pytest) -vv qforce
        coverage xml
        codecov
